## Analysis for "families with kids waste more"-hypothesis 
## + Identify sample size (mean varies <5%)

```{r}
#0. you might have to install missing packages, comment in the following 2 lines to do so
#install.packages("RColorBrewer")
#install.packages("tidyverse")
library(RColorBrewer)
library(tidyverse)

library(dplyr)
library(purrr)
save_plots = TRUE

#4. optional: change the design settings: 
PALETTE = "Spectral"
WIDTH = 1200
HEIGHT = 900
OUTPUT_FOLDER = "plots/"
```

```{r}
  # Set the parent folder path

PATH <- "E:/UF/ifwaste/data/"

setup_dataset<- function(PATH,foldername) {
  # Get the list of subfolder paths
  subfolder_paths <- list.files(paste0(PATH,foldername), full.names = TRUE)
  # Get the list of unique file names across all subfolders
  unique_file_names <- subfolder_paths %>%
    map(~ list.files(., pattern = "\\.csv$", full.names = TRUE)) %>%
    unlist() %>%
    basename() %>%
    unique()
  # Create individual data frames for each unique file name
  df <- unique_file_names %>%
    set_names() %>%
    map(~ {
      file_name_with_slash <- paste0("/",.x)  # Add "/" before unique filename
      # Print the pattern being used
      file_paths <- subfolder_paths %>%
        map(~ {
          files <- (paste0(.x, file_name_with_slash))
        }) %>%
        unlist() %>%
        discard(~ length(.x) == 0)
      map_dfr(file_paths, read.csv,.id = "Run")
    })
  names(df) <- str_remove(names(df), "....$")

  #group by house an run 
  df[["wasted"]]$Group <- paste(df[["wasted"]]$Run,df[["wasted"]]$House,sep="_")
  wasted <- df[["wasted"]] #for now only the wasted subfolder is relevant
  wasted_edited <- data.frame(Day.Wasted=0:max(wasted$Day.Wasted))

  waste_hh_day <- summarise(group_by(wasted, Group,Day.Wasted), Kg=sum(Kg))

  # Pivot original_df to wide format based on group
  pivoted_df <- pivot_wider(waste_hh_day, names_from = Group, values_from = Kg)

  # Merge pivoted_df with wasted_edited
  wasted_edited <- merge(wasted_edited, pivoted_df, by = "Day.Wasted", all.x = TRUE)

  #ensure NA => 0
  wasted_edited <- replace(wasted_edited, is.na(wasted_edited), 0)

  Mean <- rowMeans(wasted_edited[, -1])
  Lower <- apply(wasted_edited[,-1], 1,min)
  Upper <- apply(wasted_edited[,-1],1, max)
  Std <- apply(wasted_edited[,-1], 1, sd)

  wasted_edited$Mean <- Mean
  wasted_edited$Lower <- Lower
  wasted_edited$Upper<- Upper
  wasted_edited$Std<- Std
  return(wasted_edited)
}



plot_lower_upper <- function(df, label, plot = NULL) {
  START = 10
    if (is.null(plot)){
        plot <- ggplot(df, aes(x = Day.Wasted, y = Mean)) +
            geom_ribbon(aes(ymin = Lower, ymax = Upper, fill = label), alpha = 0.25, show.legend=FALSE) +
            geom_line(aes(color = label)) + #thicker lines: size=1.5
            labs(x = "Day", y = "Kg", color = "Household with...") +  # Specify legend titles
            xlim(START, max(df$Day.Wasted))   # Specify the range of x-axis +
           # scale_fill_discrete()
    }
    else {
        plot <- plot + 
            geom_ribbon(data = df, aes(ymin = Lower, ymax = Upper, fill = label), alpha = 0.25, show.legend=FALSE) +
            geom_line(data = df, aes(x = Day.Wasted, y = Mean, color = label)) +
            labs(x = "Day", y = "Kg", color =  "Household with...") +  # Specify legend titles
            xlim(START, max(df$Day.Wasted))   # Specify the range of x-axis
           # scale_fill_discrete()
    }

    
    return(plot)
}

```



```{r}
colors <- brewer.pal(11, PALETTE)[1:4]  # Select the first 4 colors from the Spectral palette

df_waste_6 <- setup_dataset(PATH,"6_kids/")
df_waste_4 <- setup_dataset(PATH,"4_kids/")
df_waste_2 <- setup_dataset(PATH,"2_kids/")
df_waste_0 <- setup_dataset(PATH,"0_kids/")

```

```{r}
plot = NULL

plot <- plot_lower_upper(df_waste_6,"6 kids",plot)
plot <- plot_lower_upper(df_waste_4,"4 kids",plot)
plot <- plot_lower_upper(df_waste_2,"2 kids",plot)
plot <- plot_lower_upper(df_waste_0,"no kids",plot)

plot



```
```{r}

#lower_bound <- NULL
#upper_bound <- NULL
## Calculate confidence interval for each Day.Wasted category
#conf_intervals <- sapply(1:(max(df_waste_0$Day.Wasted)+1), function(i) {
#  z <- qnorm(0.975)  # Z-score for 95% confidence interval (two-tailed)
  #count sample number
#  exp <- grep("_", names(df_waste_0), value = TRUE)
#  n <- ncol(df_waste_0[, exp])
#  sample_size <- rep(n,max(df_waste_0$Day.Wasted)+1)
##  margin_of_error <- z * ( df_waste_0$Std[i] / sqrt(sample_size))
#  lower_bound <-  df_waste_0$Mean[i] - margin_of_error
#  upper_bound <-  df_waste_0$Mean[i] + margin_of_error
#  print(lower_bound)
#})

```

```{r}

  calculate_confidence_interval <- function(df) {

    new_df <- data.frame(Day.Wasted = 0:max(df$Day.Wasted))

    # Create empty columns for Lower and Upper
    new_df$Lower <- NA
    new_df$Upper <- NA

    # Calculate confidence interval for each Day.Wasted category
    for (i in 1:(max(df$Day.Wasted) + 1)) {
      z <- qnorm(0.975)  # Z-score for 95% confidence interval (two-tailed)
      
      # Filter data for the current day
      day_data <- subset(df, Day.Wasted == (i - 1))
      
      # Calculate sample size for the current day
      exp <- grep("_", names(day_data), value = TRUE)
      n <- ncol(day_data[, exp])
      
      # Calculate sample size for the current day
      sample_size <- n
      
      # Calculate mean and standard deviation for the current day
      mean_val <- mean(day_data$Mean)
      std_val <- mean(day_data$Std)
      
      # Calculate margin of error and confidence interval
      margin_of_error <- z * (std_val / sqrt(sample_size))
      lower_bound <- mean_val - margin_of_error
      upper_bound <- mean_val + margin_of_error
      
      # Assign confidence interval values to new_df
      new_df[i, "Lower"] <- lower_bound
      new_df[i, "Upper"] <- upper_bound
    }

    new_df$Mean <- df$Mean
    return(new_df)

  }

```

```{r}
df_waste_0_ci <- calculate_confidence_interval(df_waste_0)
df_waste_2_ci <- calculate_confidence_interval(df_waste_2)
df_waste_4_ci <- calculate_confidence_interval(df_waste_4)
df_waste_6_ci <- calculate_confidence_interval(df_waste_6)


plot2 = NULL

##TODO this code is completely ignoring my selected colors

plot2 <- plot_lower_upper(df_waste_6_ci,"6 kids",plot2)
plot2 <- plot_lower_upper(df_waste_4_ci,"4 kids",plot2)
plot2 <- plot_lower_upper(df_waste_2_ci,"2 kids",plot2)
plot2 <- plot_lower_upper(df_waste_0_ci,"no kids",plot2)

plot2

```






## Check if average still changes 
```{r}

#default #10hh per run 
df_waste_0_2 <- setup_dataset(PATH,"0_kids_40/") #20hh per run 
df_waste_0_3 <- setup_dataset(PATH,"0_kids_50hh/") #50hh per run
plot3 <- NULL

plot3 <- plot_lower_upper(df_waste_0,"",plot3)
plot3 <- plot_lower_upper(df_waste_0_2,"",plot3)
plot3 <- plot_lower_upper(df_waste_0_3,"",plot3)

plot3
```

```{r}

Mean <- rowMeans(df_waste_0[, -1])
mean(Mean)
Mean2 <- rowMeans(df_waste_0_2[, -1])
mean(Mean2)

Mean3 <- rowMeans(df_waste_0_3[, -1])
mean(Mean3)


mean(Mean2)/mean(Mean)
mean(Mean3)/mean(Mean2)


```